### ISSUE TITLE
How to insert data to database?

### ISSUE THREAD

**Issue by LocalHeroPro** [KKSzymanowski/laravel-6-firebird#1]
I can't insert new data to table:
```php
DB::connection('firebird')
            ->table('table_name')
            ->insert([
                'param_1' => 1,
                'param_2' => 1,
                'param_3' => 2,
                'param_4' => 12,
                'param_5' => 22
            ]);
```
I don't even get error message.
I can normally fetch data.

**Comment by KKSzymanowski** [comment]
As stated in the readme, I never needed to insert anything to a Firebird database so this package isn't tested for that. 
I don't have my PC by with me right now but I will try to replicate this tomorrow. If you find anything by that time please let me know.

**Comment by KKSzymanowski** [comment]
@LocalHeroPro I have tested it with this [docker image](https://hub.docker.com/r/jacobalberty/firebird) and I have no issues:

I have created the following table:
```sql
create table USERS
(
    ID INTEGER not null constraint USERS_PK primary key,
    NAME VARCHAR(255)
);
```
Then I inserted a record manually to see if this works:
```sql
INSERT INTO users (id, name) VALUES (1, 'foo');
```
Then I inserted another record with Laravel:
```php
DB::connection('firebird')->table('USERS')->insert(['ID' => 2, 'NAME' => 'bar']);
```
The record has been correctly inserted and it shows up in the result of the following query:
```sql
SELECT * FROM users;
```
![image](https://user-images.githubusercontent.com/13980973/75349897-d71be880-58a5-11ea-9f99-e9258ed03fd6.png)

Make sure you correctly capitalize column and table names. In my case I had to specify everything in uppercase. I had to do this because Laravel wraps table and column names in double quotes to avoid conflicts with keywords like `ORDER`. This behaviour results in having to pass the names exactly as they're stored in the database which is uppercase in the case of Firebird.

The thing which concerns me is that you didn't get any error messages. Where did you run the insert? Tinker, HTTP Controller, Artisan Command? Did you check the Laravel logs?

**Comment by LocalHeroPro** [comment]
Ok, simple `insert` work as expected.

How about other methods, did you consider to develop that repository with another methods for DB Query and Eloquent ORM?

**Comment by KKSzymanowski** [comment]
What methods do you have in mind? I've successfully ran raw queries and used Eloquent models for communication with Firebird databases. What is missing in your opinion?

**Comment by LocalHeroPro** [comment]
I'm trying using
```php
DB::connection('firebird')
    ->table('TABLE_NAME')
    ->where('ID, '=', 15)
    ->exists();
```
with failure:
![2020-02-29 (2)](https://user-images.githubusercontent.com/42643563/75611951-6b44b480-5b1f-11ea-8364-fae1dd1f80ad.png)

and for example:
```php
ModelName::FirstOrCreate(
    ['id' => 11],
    ['some_field' => 12]
    )
```
![2020-02-29](https://user-images.githubusercontent.com/42643563/75611980-a941d880-5b1f-11ea-83b8-6cc7780a7156.png)

So few methods are missing.

**Comment by KKSzymanowski** [comment]
I'm afraid "last insert id" is not supported by firebird: http://www.firebirdfaq.org/faq243/

As for the `exists` error I'll do some research. Maybe there's a way to get around.

**Comment by LocalHeroPro** [comment]
I have 'quick fix' for that:
```php
$exist = (bool)DB::connection('firebird')
    ->table('TABLE_NAME')
    ->where('ID, '=', 15)
    ->count();
```

But for me more interesting is that you want to develop your package? ;)

**Comment by KKSzymanowski** [comment]
I've done some digging and I think I can incorporate a similar fix to the package. I'll submit a PR later today and would ask you to test it in your environment.

**Comment by KKSzymanowski** [comment]
I'll release a new version with the `exists()` support, updated readme and Laravel 7 support later today.
